#release configuration
#Tue Nov 28 20:11:19 CET 2017
remoteTagging=true
project.rel.de.spoeth\:ra-utilities=1.0
scm.commentPrefix=[maven-release-plugin] 
project.scm.de.spoeth\:ra-utilities.tag=HEAD
project.dev.de.spoeth\:ra-utilities=1.1-SNAPSHOT
completedPhase=generate-release-poms
scm.url=scm\:git\:https\://github.com/ralfspoeth/rar-utilities.git
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
scm.tag=ra-utilities-1.0
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
project.scm.de.spoeth\:ra-utilities.developerConnection=scm\:git\:https\://github.com/ralfspoeth/rar-utilities.git
